config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :new, :create]
  resource :session, only: [:new, :destroy, :create]
  resources :bands do
    resource :albums, only: [:new]
  end

  resource :albums, except: [:index] do
    resources :tracks, only: [:new]
  end

  resources :tracks, except: [:index]

  root to: redirect('/bands')
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id      :integer          not null, primary key
#  band_id :integer          not null
#  title   :string           not null
#  year    :integer          not null
#  live    :boolean
#

class Album < ApplicationRecord
  belongs_to :band,
    class_name: 'Band',
    foreign_key: :band_id

  has_many :tracks,
    class_name: 'Track',
    foreign_key: :album_id

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  has_many :albums,
    class_name: 'Albums',
    foreign_key: :band_id

  has_many :tracks,
    through: :albums,
    source: :tracks

end

app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id        :integer          not null, primary key
#  album_id  :integer          not null
#  title     :string           not null
#  track_num :integer          not null
#  bonus     :boolean
#

class Track < ApplicationRecord
  belongs_to :album,
    class_name: 'Album',
    foreign_key: :album_id

  has_one :band,
    through: :album,
    source: :band
    
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#

class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :password, length: {minimum: 6, allow_nil: true}
  validates :password_digest, presence: true
  validates :session_token, presence: true, uniqueness: true
  after_initialize :ensure_session_token

  attr_reader :password

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)

    return nil if user == nil
    user.is_password?(password) ? user : nil
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  private
  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :logged_in?
  helper_method :current_user

  def logged_in?
    !current_user.nil?
  end

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
    @current_user = nil
  end

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :ensure_logged_in

  def new
    @band = Band.new
    render :new
  end

  def index
    render :index
  end

  def ensure_logged_in
    if !logged_in?
      redirect_to new_session_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )

    if user.nil?
      flash[:errors] = ["Incorrect login/password"]
      render :new
    else
      login_user!(user)
      redirect_to bands_url
    end
  end

  def new
    render :new
  end

  def destroy
    logout
    redirect_to new_session_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login_user!(@user)
      redirect_to bands_url
    else
      flash[:errors] = ["That user already exists"]
      render :new
    end
  end

  def show
    render :show
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bands/index.html.erb
<h1>HI!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <img src="https://i.pinimg.com/736x/68/e8/7e/68e87eaa39e4308d69c1844287177f95--shake-shack-burger-logo-food.jpg" alt="Music logo">
    Music App

    <div class="login">
    <% if logged_in? %>
        <p>Welcome, <%= current_user.email %></p>
        <form action="<%= session_url %> " method="POST">
          <input type="hidden" name="authenticity_token" method="<%=form_authenticity_token%>">
          <input type="hidden" name="_method" value="delete">
          <input type="submit" value="Logout">
        </form>
    <% else %>
      <a href="<%= new_session_url %>">Sign in</a>
      <a href="<%= new_user_url %>">Sign up</a>
    <% end %>
    </div>

  </header>

  <body>
    <% if flash[:errors] %>
     <ul>
       <% flash[:errors].each do |error| %>
         <li><%= error %></li>
       <% end %>
     </ul>
   <% end %>

    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<section class="page">
<h1>Create new user!</h1>

<p></p>
<form action=" <%= users_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="user_email">Enter your EMail:</label>
  <input type="text" name="user[email]" id="user_email" value="<% @user.email %>">
  <br>
  <br>
  <label for="user_email">Choose a password:</label>
  <input type="password" name="user[password]" id="user_password" value="<% @user.password %>">
  <br>
  <br>
  <input type="submit" value="Create User!">
</form>
</section>